// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import CartItemsController from "./cart_items_controller"
application.register("cartitems", CartItemsController)

import CartsController from "./carts_controller"
application.register("carts", CartsController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import SearchController from "./search_controller"
application.register("search", SearchController)